name: Deploy on Develop

on:
  push:
    branches: main

jobs:
  deploy: # App deploy
    name: Deploy to Development
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Development
      uses: appleboy/ssh-action@master
      with:
        username: ${{ secrets.SSH_USER }}
        host: ${{ secrets.SSH_HOST }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: 'cd /var/www && ./f1_server_deploy.sh f1_2022'
